version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - 28017
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - MONGO_URI=mongodb://mongodb/exampleDb
    links:
      - mongodb
    ports:
     - 9000
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 3000
      - 443